routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AgentController;
use App\Http\Controllers\CallController;
use App\Http\Controllers\CallEntryController;
use App\Http\Controllers\CollectionController;
use App\Http\Controllers\DateController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\KeywordController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\PlaceController;

use App\Models\Collection;
use App\Models\Date;
use App\Models\Image;
use App\Models\Keyword;
use App\Models\Place;

use AnthonyMartin\GeoLocation\GeoPoint;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $request) {
    $images_otd = [];
    $total_count = Image::count();

    while (count($images_otd) <= 6) {
        srand(floor(time()/86400)+count($images_otd));
        $image = Image::find(rand(0, $total_count));
        $images_otd[] = $image;
    }

    return view('frontend/home', [
        'tagcloud' => $request->has('tagcloud'),
        'collections' => Collection::where('origin', 'pia')->latest()->take(20)->get(),
        'images_otd' => $images_otd
    ]);
});

Route::resource('collections', CollectionController::class);
Route::resource('images', ImageController::class);
Route::resource('keywords', KeywordController::class);
Route::resource('agents', AgentController::class);
Route::resource('places', PlaceController::class);
Route::resource('notes', NoteController::Class);
Route::resource('maps', MapController::Class);
Route::resource('calls', CallController::Class);
Route::resource('callentries', CallEntryController::Class);
Route::resource('dates', DateController::Class);

Route::get('/calls/{id}/entry', [CallController::class, 'entry'])->name('maps.images');

Route::get('/images/{id}/similar', [ImageController::class, 'findSimilar'])->name('images.similar');

Route::get('/maps/{id}/images', [MapController::class, 'images'])->name('maps.images');
Route::patch('/maps/{id}/imagesUpdate', [MapController::class, 'imagesUpdate'])->name('maps.imagesUpdate');

Route::get('/collections/{id}/csv',
    [FrontendController::class, 'csv'])->name('collections.csv');
Route::post('/collections/{id}/upload-image',
    [CollectionController::class, 'uploadImage'])->name('collections.uploadImage');
Route::post('/collections/{id}/upload-documents',
    [CollectionController::class, 'uploadDocuments'])->name('collections.uploadDocuments');
Route::get('/collections/{id}/map',
    [CollectionController::class, 'map'])->name('collections.map');
Route::get('/collections/{id}/copy',
    [CollectionController::class, 'copy'])->name('collections.copy');
Route::post('/collections/{id}/do-copy',
    [CollectionController::class, 'doCopy'])->name('collections.doCopy');
Route::get('/collections/{id}/timeline',
    [CollectionController::class, 'timeline'])->name('collections.timeline');
Route::get('/collections/{id}/memory',
    [CollectionController::class, 'memory'])->name('collections.memory');
Route::get('/collections/{id}/export',
    [CollectionController::class, 'export'])->name('collections.export');

Route::get('/by-coordinates', function (Request $request) {
    return view('frontend/partials/search-by-coordinates');
})->name('search.byCoordinates');
Route::get('/by-dates', function (Request $request) {
    return view('frontend/partials/search-by-dates');
})->name('search.byDates');

Route::get('/nearby', function(Request $request) {
    if ($request->latitude) {

        $geopoint = new GeoPoint($request->latitude, $request->longitude);
        $bounding_box = $geopoint->boundingBox($request->distance / 1000, 'km');

        $places = Place
            ::where('longitude', '>=', $bounding_box->getMinLongitude())
            ->where('latitude', '>=', $bounding_box->getMinLatitude())
            ->where('longitude', '<=', $bounding_box->getMaxLongitude())
            ->where('latitude', '<=', $bounding_box->getMaxLatitude())
            ->get();

        $image_ids = [];

        foreach($places as $key => $place) {
            foreach($place->images as $key => $image) {
                array_push($image_ids, $image->id);
            }
        }

        return view('frontend/nearby', [
            'images' => Image::whereIn('id', $image_ids)->get()
        ]);
    }

    return view('frontend/nearby');
});

/* custom error handling */
Route::fallback(function() {
    return view('errors/404', [
        'image' => Image::inRandomOrder()->first(),
        'collections' => Collection::inRandomOrder()->limit(3)->get(),
        'keywords' => Keyword::inRandomOrder()->limit(3)->get()
    ]);
});

/* statistics */
Route::get('/stats', function(Request $request) {
    $images_total = Image::count();

    $images_wo_date = Image::doesnthave('date')->count();
    $images_wo_location = Image::doesnthave('place')->count();
    $images_wo_keywords = Image::doesnthave('keywords')->count();

    $images_wo_date_location = Image::doesnthave('date')->where('place_id', null)->count();
    $images_wo_keywords_location = Image::doesnthave('keywords')->where('place_id', null)->count();
    $images_wo_date_keywords = Image::doesnthave('keywords')->doesnthave('dates')->count();
    $images_wo_date_keywords_location = Image::doesnthave('keywords')->doesnthave('date')->where('place_id', null)->count();

    $images_w_date_location = Image::has('date')->where('place_id', '!=', null)->count();
    $images_w_date_keywords = Image::has('date')->has('keywords')->count();
    $images_w_keywords_location = Image::has('keywords')->where('place_id', '!=', null)->count();
    $images_w_date_keywords_location = Image::has('keywords')->has('date')->where('place_id', '!=', null)->count();

    $images_w_acc_1 = Image::whereHas('date', function($q){
        $q->where('accuracy', '1');
    })->count();
    $images_w_acc_2 = Image::whereHas('date', function($q){
        $q->where('accuracy', '2');
    })->count();
    $images_w_acc_3 = Image::whereHas('date', function($q){
        $q->where('accuracy', '3');
    })->count();
    $images_w_date_range = Image::whereHas('date', function($q){
        $q->whereNotNull('end_date');
    })->count();

//number_format(100 / $images * $images_wo, 2)

    echo('<table cellpadding="8" border style="font-family: sans-serif;">');
    echo('<tr>');
    echo('<td>Total Image Count</td>');
    echo('<td>'.number_format($images_total, 0, '.', '\'').'</td>');
    echo('<td></td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images without date</td>');
    echo('<td>'.number_format($images_wo_date, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date, 0, '.', '\'').'% (of total images)</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without location</td>');
    echo('<td>'.number_format($images_wo_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without keywords</td>');
    echo('<td>'.number_format($images_wo_keywords, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images with neither date nor a location</td>');
    echo('<td>'.number_format($images_wo_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with neither keywords nor a location</td>');
    echo('<td>'.number_format($images_wo_keywords_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with neither date nor keywords</td>');
    echo('<td>'.number_format($images_wo_date_keywords, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without anything</td>');
    echo('<td>'.number_format($images_wo_date_keywords_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images with date and location</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_date_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with keywords and location</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with date and keywords</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_date_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with everything</td>');
    echo('<td>'.number_format($images_w_date_keywords_location, 0, '.', '\'').'</td>');

resources/views/collections/copy.blade.php
@extends('base')

@section('content')
<div class="p-4">
    <div class="md:flex mb-4">
        <div class="md:w-1/2">
            <h2 class="text-2xl mb-2">
                {{ $collection->label }}
            </h2>
            <div>
                <x-links.cta label="Back" :href="route('collections.show', [$collection])"/>
            </div>
        </div>
        
    </div>
    <div class="w-full mb-10">
        {!! $collection->description !!}
    </div>
    <form action="{{ route('collections.doCopy', [$collection]) }}" method="POST" class="flex">
        @csrf

        <div class="w-1/4 pr-4">
            <p class="text-xs mb-2">Choose the collection to which you want to copy the images you selected on the right. Leave empty and enter a label to start a new collection.</p>

                <label for="collection_id">Collection…</label>
                <select name="collection_id" id="collection_id" class="w-full text-xs px-2 bg-black text-white rounded-full" style="height: 26px;">
                    <option value="">-</option>
                    @foreach ($collections as $c)
                        @if($c->origin != 'salsah')
                            <option value="{{ $c->id }}">{{ $c->label }}</option>
                        @endif
                    @endforeach
                </select>
                <label for="collection_label" class="mt-2 inline-block">… or collection label</label>
                <input type="text" name="collection_label" class="w-full text-xs px-2 border border-black rounded-full mb-4" style="height: 26px;" paceholder="Collection label">
                <button type="submit">Copy</button>
        </div>
        <div class="w-3/4">
            <div class="grid gap-4 grid-flow-row grid-cols-1 md:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">
                @foreach ($collection->images as $image)
                    <div class="relative">
                        <img class="inline-block mb-2 w-full" src="https://sipi.participatory-archives.ch/{{$image->base_path != '' ? $image->base_path.'/' : ''}}{{$image->signature}}.jp2/full/320,/0/default.jpg" alt="{{$image->title}}" title="{{$image->title}}">
                        <input type="checkbox" name="image_{{ $image->id }}" class="absolute top-2 right-2 cursor-pointer" style="width: 30px; height: 30px">
                    </div>
                @endforeach
            </div>
        </div>

    </form>
</div>
@endsection

resources/views/collections/edit.blade.php
@extends('base')

@section('content')
<div class="bg-gray-100 min-h-screen" x-data="{cols: 3}">
    <div class="flex" id="searchable-list" >
        <div class="fixed bg-black h-screen w-1/2 p-4 overflow-y-auto">
            <div>
                <section class="my-10 print-hidden">
                    <div class="flex gap-6 items-center">
            
                        <input type="text" name="query" placeholder="Search collection"
                            class="search py-2 px-6 w-2/3 border border-gray-700 rounded-full focus:outline-none text-lg z-10">
                        
                        <input type="range" min="1" max="6" x-model="cols">
                </section>
            
                <main>
                    <div id="images" class="pb-20">
                        @include('collections.partials.display-grid', ['images' => $collection->images])
                    </div>
                </main>
            </div>
        </div>

        <div class="fixed left-1/2 h-screen w-1/2 pr-36 bg-white overflow-y-auto">
            <form method="POST" action="{{ route('collections.update', [$collection]) }}">
                @csrf
                @method('patch')

                <div class="p-14 pr-0">
                    <div class="mb-12">
                        <label for="label" class="block">Label</label>
                        <input name="label" class="text-4xl border border-gray-500 p-2 w-full" value="{{ $collection->label ?? '' }}" placeholder="Label"/>
                    </div>
                    <div class="w-full mb-4">
                        <label for="creator" class="block">Creator</label>
                        <input name="creator" class="border border-gray-500 p-2 w-full" value="{{ $collection->creator ?? '' }}" placeholder="Who created this collection?"/>
                    </div>
                    <div class="w-full mb-4">
                        <label for="description" class="block">Description</label>
                        <textarea name="description" id="description" class="border border-gray-500 p-2 w-full" oninput="auto_grow(this)" placeholder="What can you say about this collection?">{{ $collection->description ?? '' }}</textarea>
                    </div>
                    <div class="w-full">
                        <label for="keywords[]" class="block">Keywords</label>
                        <select name="keywords[]" class="w-full slim" multiple>
                            <option value="">-</option>
                            @foreach ($keywords as $keyword)
                                <option value="{{ $keyword->id }}" {{ $collection->keywords->contains($keyword->id) ? 'selected' : '' }}>{{ $keyword->label }}</option>
                            @endforeach
                        </select>
                    </div>

                </div>

                <div class="flex justify-between fixed bottom-0 left-1/2 w-1/2 pl-8 py-2 pr-28 border-t leading-10 border-gray-700 bg-white">
                    <button type="submit" class="hover:underline">Save info</button>
                </div>
            </form>
        </div>
    </div>

    <aside id="sidebar"
        x-data="{expand_collections: false}"
        @mouseleave="expand_collections = false;"
        class="flex fixed top-0 right-0 transform transition min-h-screen shadow-2xl z-50 print-hidden">
        
        <livewire:collections-aside />
    </aside>
</div>
@endsection

@section('scripts')
    <script>

        document.addEventListener('DOMContentLoaded', () => {
            auto_grow(document.querySelector('#description'));

            document.querySelectorAll('textarea').forEach(el => {
                el.style.height = "5px";
                el.style.height = (el.scrollHeight)+"px";
            })
        
            let creator = document.querySelector('[name="creator"]');

            if(creator.value == '' && localStorage.getItem('collection_creator') != '') {
                creator.value = localStorage.getItem('collection_creator');
            }

            creator.addEventListener('change', () => {
                localStorage.setItem('collection_creator', creator.value);
            })

            document.querySelectorAll('select.slim').forEach(el => {
                console.log(el)
                new SlimSelect({
                    select: el,
                });
            });

        });

        function auto_grow(element) {
            element.style.height = "5px";
            element.style.height = (element.scrollHeight)+"px";
        }

    </script>
@endsection
        

resources/views/collections/index.blade.php
@extends('base')

@section('content')
<div class="p-4 pb-20">
    <div class="md:flex mb-4">
        <h2 class="text-2xl mb-2 md:w-1/2">
            Collections
        </h2>
        
    </div>
    @php
        $current = '';
    @endphp
    <div id="searchable-list">
        <input class="search border-b border-black mb-8 focus:outline-none" placeholder="Search…"/>
        <ul class="list">
            @foreach ($collections as $collection)
                @if ($collection->label)
                    @if ($current != $collection->label[0])
                        @php
                            $current = $collection->label[0];
                        @endphp
                        <h2 class="text-2xl mt-2 mb-2">{{ $current }}</h2>
                    @endif
                    <li class="inline">
                        <x-links.default :label="$collection->label" href="{{ route('collections.show', [$collection]) }}"
                            class="mb-2 label"/>
                    </li>
                @endif
            @endforeach
        </ul>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('node_modules/list.js/dist/list.min.js') }}"></script>
    <script>

        document.addEventListener('DOMContentLoaded', () => {
            var searchable_list = new List('searchable-list', {
                valueNames: ['label']
            });
        });

    </script>
@endsection

resources/views/collections/map.blade.php
@extends('base')

@section('content')
<div class="p-4">
    <div class="md:flex mb-4">
        <div class="md:w-1/2">
            <h2 class="text-2xl mb-2">
                {{ $collection->label }}
            </h2>
            <div>
                <x-links.cta label="Back" :href="route('collections.show', [$collection])"/>
            </div>
        </div>
        
    </div>
    <div class="w-full mb-10">
        {!! $collection->description !!}
    </div>
    <div class="flex">
        <div class="w-1/4 pr-4">
            <p class="text-xs mb-2">These images do not have a location attached.</p>
            @foreach ($collection->images as $image)
                @if (!$image->place)
                <a href="{{ route('images.show', [$image]) }}">
                    <img class="inline-block mb-2 w-full" src="https://sipi.participatory-archives.ch/{{$image->base_path != '' ? $image->base_path.'/' : ''}}{{$image->signature}}.jp2/full/320,/0/default.jpg" alt="{{$image->title}}" title="{{$image->title}}">
                </a>
                @endif
            @endforeach
        </div>
        <div class="w-3/4">
            @include('collections.image-actions')
            <div id="map" class="w-full" style="height: 800px"></div>
        </div>
    </div>
</div>

@endsection

resources/views/collections/memory.blade.php
@extends('base')

@section('content')


<style>

.image {
    cursor: pointer;
}

.image:after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: #232323;
}

.image.open:after,
.image.solved:after {
    content: none;
}

</style>

<main>

    <div class="text-center p-10">

    @foreach($images as $image)

        <div id="image-{{ $image->id }}" class="inline-block relative bg-cover bg-center image image-{{ $image->id }}" style="height: 300px; width: 300px; background-image: url('https://sipi.participatory-archives.ch/{{$image->base_path != '' ? $image->base_path.'/' : ''}}{{$image->signature}}.jp2/full/320,/0/default.jpg')">
        </div>

    @endforeach

    </div>

</main>

<div class="overlay hidden fixed top-0 left-0 w-full h-full bg-red-500 opacity-10"></div>

<script>

let images = document.querySelectorAll('.image'),
    turn_count = 0;
    card_1 = undefined, card_2 = undefined;

for(let i = 0; i < images.length; i++){
    let image = images[i];

    image.addEventListener('click', (evt) => {
        let target = evt.currentTarget;

        if(!target.classList.contains('solved') || !target.classList.contains('open')) {

            evt.currentTarget.classList.add('open');

            if(card_1 != undefined) {
                turn_count++;

                card_2 = target;

                if(card_1.id == card_2.id) {
                    card_1.classList.remove('open');
                    card_2.classList.remove('open');

                    card_1.classList.add('solved');
                    card_2.classList.add('solved');

                    card_1 = undefined;
                    card_2 = undefined;

                    if(document.querySelectorAll('.image').length == document.querySelectorAll('.image.solved').length) {
                        alert('Yay, du häsches gschafft … Gnueg Arbeit für hüt, ab is Bier 🥳 🍻 Hesch nur '+turn_count+' Züg brucht.');
                    }
                } else {
                    document.querySelector('.overlay').classList.remove('hidden');
                    setTimeout(() => {
                        card_1.classList.remove('open');
                        card_2.classList.remove('open');

                        card_1 = undefined;
                        card_2 = undefined;

                        document.querySelector('.overlay').classList.add('hidden');
                    }, 2000);
                }
            } else {
                card_1 = target;
            }
        }
    })
}

</script>

@endsection

resources/views/collections/show.blade.php
@extends('base')

@section('content')
<div class="bg-gray-100 md:min-h-screen">
    <div class="flex flex-col md:flex-row" id="searchable-list" >
        <div class="md:fixed bg-black md:h-screen md:w-1/2 {{ !in_array($display, ['map', 'timeline']) ? 'p-4 md:overflow-y-auto' : 'overflow-hidden' }}">
            <div>
                @if(!in_array($display, ['map', 'timeline']))
                <section class="my-10 print-hidden">
                    <div class="flex gap-6 items-center">
            
                        <input type="text" name="query" placeholder="Search collection"
                            class="search hidden md:inline-block py-2 px-6 w-2/3 border border-gray-700 rounded-full focus:outline-none text-lg z-10">
                        
                        @include('collections.partials.image-actions')
                </section>
                @endif
            
                <main>
                    <div id="images" class="{{ !in_array($display, ['map', 'timeline']) ? 'pb-20' : 'min-h-screen' }}">
                        @if($display == 'list')
                            @include('collections.partials.display-list')
                        @elseif($display == 'map')
                            @include('collections.partials.display-map', ['images' => $collection->images])
                        @elseif($display == 'timeline')
                            @include('collections.partials.display-timeline')
                        @else
                            @include('collections.partials.display-grid', ['images' => $collection->images])
                        @endif
                    </div>
                </main>
            </div>
        </div>

        <div class="md:fixed md:left-1/2 h-screen md:w-1/2 md:pr-16 bg-white md:overflow-y-auto">
            @include('collections.partials.collection-info')

            <div class="flex flex-col md:flex-row justify-between md:fixed bottom-0 md:left-1/2 md:w-1/2 p-4 pb-20 md:pr-20 md:pb-4 border-t leading-10 border-gray-700 bg-white">
                <a href="/?cid={{ $collection->id }}" class="hover:underline">Edit selection</a>

                <a href="{{ route('collections.edit', [$collection]) }}" class="hover:underline">Edit info</a>

                <form id="images-form" class="hidden" method="POST" enctype="multipart/form-data" action="{{ route('collections.uploadImage', [$collection]) }}">
                    @csrf
                    <input id="images-upload" onchange="document.querySelector('#images-form').submit()" class="hidden" type="file" name="images[]" accept="image/*" required multiple>
                </form>

                <button type="button" onclick="document.querySelector('#images-upload').click()" title="Add images to collection" class="hover:underline text-left">
                    Add images
                </button>

                <a href="{{ route('collections.copy', [$collection]) }}" title="Copy images to new collection" class="hover:underline">
                    Copy images
                </a>

                @if($collection->origin != 'salsah')
                <form action="{{ route('collections.destroy', [$collection]) }}" method="post" class="inline-block">
                    @csrf
                    @method('delete')

                    <x-buttons.delete/>
                </form>
                @endif
            </div>
        </div>
    </div>

    <aside id="sidebar"
        x-data="{expand_collections: false}"
        @mouseleave="expand_collections = false;"
        class="flex fixed top-0 right-0 transform transition min-h-screen shadow-2xl z-50 print-hidden">
        
        <livewire:collections-aside />
    </aside>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('node_modules/list.js/dist/list.min.js') }}"></script>
    <script>

        document.addEventListener('DOMContentLoaded', () => {
            var searchable_list = new List('searchable-list', {
                valueNames: ['title', 'signature', 'oldnr', 'tags']
            });
        });

    </script>
@endsection