routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AgentController;
use App\Http\Controllers\CallController;
use App\Http\Controllers\CallEntryController;
use App\Http\Controllers\CollectionController;
use App\Http\Controllers\DateController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\KeywordController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\PlaceController;

use App\Models\Collection;
use App\Models\Date;
use App\Models\Image;
use App\Models\Keyword;
use App\Models\Place;

use AnthonyMartin\GeoLocation\GeoPoint;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $request) {
    $images_otd = [];
    $total_count = Image::count();

    while (count($images_otd) <= 6) {
        srand(floor(time()/86400)+count($images_otd));
        $image = Image::find(rand(0, $total_count));
        $images_otd[] = $image;
    }

    return view('frontend/home', [
        'tagcloud' => $request->has('tagcloud'),
        'collections' => Collection::where('origin', 'pia')->latest()->take(20)->get(),
        'images_otd' => $images_otd
    ]);
});

Route::resource('collections', CollectionController::class);
Route::resource('images', ImageController::class);
Route::resource('keywords', KeywordController::class);
Route::resource('agents', AgentController::class);
Route::resource('places', PlaceController::class);
Route::resource('notes', NoteController::Class);
Route::resource('maps', MapController::Class);
Route::resource('calls', CallController::Class);
Route::resource('callentries', CallEntryController::Class);
Route::resource('dates', DateController::Class);

Route::get('/calls/{id}/entry', [CallController::class, 'entry'])->name('maps.images');

Route::get('/images/{id}/similar', [ImageController::class, 'findSimilar'])->name('images.similar');

Route::get('/maps/{id}/images', [MapController::class, 'images'])->name('maps.images');
Route::patch('/maps/{id}/imagesUpdate', [MapController::class, 'imagesUpdate'])->name('maps.imagesUpdate');

Route::get('/collections/{id}/csv',
    [FrontendController::class, 'csv'])->name('collections.csv');
Route::post('/collections/{id}/upload-image',
    [CollectionController::class, 'uploadImage'])->name('collections.uploadImage');
Route::post('/collections/{id}/upload-documents',
    [CollectionController::class, 'uploadDocuments'])->name('collections.uploadDocuments');
Route::get('/collections/{id}/map',
    [CollectionController::class, 'map'])->name('collections.map');
Route::get('/collections/{id}/copy',
    [CollectionController::class, 'copy'])->name('collections.copy');
Route::post('/collections/{id}/do-copy',
    [CollectionController::class, 'doCopy'])->name('collections.doCopy');
Route::get('/collections/{id}/timeline',
    [CollectionController::class, 'timeline'])->name('collections.timeline');
Route::get('/collections/{id}/memory',
    [CollectionController::class, 'memory'])->name('collections.memory');
Route::get('/collections/{id}/export',
    [CollectionController::class, 'export'])->name('collections.export');

Route::get('/by-coordinates', function (Request $request) {
    return view('frontend/partials/search-by-coordinates');
})->name('search.byCoordinates');
Route::get('/by-dates', function (Request $request) {
    return view('frontend/partials/search-by-dates');
})->name('search.byDates');

Route::get('/nearby', function(Request $request) {
    if ($request->latitude) {

        $geopoint = new GeoPoint($request->latitude, $request->longitude);
        $bounding_box = $geopoint->boundingBox($request->distance / 1000, 'km');

        $places = Place
            ::where('longitude', '>=', $bounding_box->getMinLongitude())
            ->where('latitude', '>=', $bounding_box->getMinLatitude())
            ->where('longitude', '<=', $bounding_box->getMaxLongitude())
            ->where('latitude', '<=', $bounding_box->getMaxLatitude())
            ->get();

        $image_ids = [];

        foreach($places as $key => $place) {
            foreach($place->images as $key => $image) {
                array_push($image_ids, $image->id);
            }
        }

        return view('frontend/nearby', [
            'images' => Image::whereIn('id', $image_ids)->get()
        ]);
    }

    return view('frontend/nearby');
});

/* custom error handling */
Route::fallback(function() {
    return view('errors/404', [
        'image' => Image::inRandomOrder()->first(),
        'collections' => Collection::inRandomOrder()->limit(3)->get(),
        'keywords' => Keyword::inRandomOrder()->limit(3)->get()
    ]);
});

/* statistics */
Route::get('/stats', function(Request $request) {
    $images_total = Image::count();

    $images_wo_date = Image::doesnthave('date')->count();
    $images_wo_location = Image::doesnthave('place')->count();
    $images_wo_keywords = Image::doesnthave('keywords')->count();

    $images_wo_date_location = Image::doesnthave('date')->where('place_id', null)->count();
    $images_wo_keywords_location = Image::doesnthave('keywords')->where('place_id', null)->count();
    $images_wo_date_keywords = Image::doesnthave('keywords')->doesnthave('dates')->count();
    $images_wo_date_keywords_location = Image::doesnthave('keywords')->doesnthave('date')->where('place_id', null)->count();

    $images_w_date_location = Image::has('date')->where('place_id', '!=', null)->count();
    $images_w_date_keywords = Image::has('date')->has('keywords')->count();
    $images_w_keywords_location = Image::has('keywords')->where('place_id', '!=', null)->count();
    $images_w_date_keywords_location = Image::has('keywords')->has('date')->where('place_id', '!=', null)->count();

    $images_w_acc_1 = Image::whereHas('date', function($q){
        $q->where('accuracy', '1');
    })->count();
    $images_w_acc_2 = Image::whereHas('date', function($q){
        $q->where('accuracy', '2');
    })->count();
    $images_w_acc_3 = Image::whereHas('date', function($q){
        $q->where('accuracy', '3');
    })->count();
    $images_w_date_range = Image::whereHas('date', function($q){
        $q->whereNotNull('end_date');
    })->count();

//number_format(100 / $images * $images_wo, 2)

    echo('<table cellpadding="8" border style="font-family: sans-serif;">');
    echo('<tr>');
    echo('<td>Total Image Count</td>');
    echo('<td>'.number_format($images_total, 0, '.', '\'').'</td>');
    echo('<td></td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images without date</td>');
    echo('<td>'.number_format($images_wo_date, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date, 0, '.', '\'').'% (of total images)</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without location</td>');
    echo('<td>'.number_format($images_wo_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without keywords</td>');
    echo('<td>'.number_format($images_wo_keywords, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images with neither date nor a location</td>');
    echo('<td>'.number_format($images_wo_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with neither keywords nor a location</td>');
    echo('<td>'.number_format($images_wo_keywords_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with neither date nor keywords</td>');
    echo('<td>'.number_format($images_wo_date_keywords, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without anything</td>');
    echo('<td>'.number_format($images_wo_date_keywords_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images with date and location</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_date_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with keywords and location</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with date and keywords</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_date_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with everything</td>');
    echo('<td>'.number_format($images_w_date_keywords_location, 0, '.', '\'').'</td>');

app/Http/Controllers/KeywordController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Keyword;

class KeywordController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('keywords/index', [
            'keywords' => Keyword::orderBy('label')->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('keywords/show', [
            'keyword' => Keyword::find($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/keywords/index.blade.php
@extends('base')

@section('content')
<div class="p-4 pb-20">
    <div class="md:flex mb-4">
        <h2 class="text-2xl mb-2 md:w-1/2">
            Keywords
        </h2>
        
    </div>

    @php
        $current = '';
    @endphp
    <div id="searchable-list">
        <input class="search border-b border-black mb-8 focus:outline-none" placeholder="Search…"/>
        <ul class="list">
        @foreach ($keywords as $keyword)
            @if ($keyword->label)
                @if ($current != $keyword->label[0])
                    @php
                        $current = $keyword->label[0];
                    @endphp
                    <h2 class="text-2xl mt-2 mb-2">{{ $current }}</h2>
                @endif
                <li class="inline">
                    <x-links.default :label="$keyword->label" :href="route('keywords.show', [$keyword])" class="mb-2 name"/>
                </li>
            @endif
        @endforeach
        </ul>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('node_modules/list.js/dist/list.min.js') }}"></script>
    <script>

        document.addEventListener('DOMContentLoaded', () => {
            var searchable_list = new List('searchable-list', {
                valueNames: ['name']
            });
        });

    </script>
@endsection

resources/views/keywords/show.blade.php
@extends('base')

@section('content')
<div class="p-4 pb-20">
    <div class="md:flex mb-4">
        <h2 class="text-2xl mb-2 md:w-1/2">
            Keyword <strong>{{ $keyword->label }}</strong>
        </h2>
    </div>

    @if($keyword->collections->count())
    <div class="mb-8">
        <h2 class="text-sm font-bold mb-2">{{ $keyword->collections->count() }} Collections</h2>
        <ul>
            @foreach($keyword->collections as $collection)
            <li class="inline">
                <x-links.default :label="$collection->label" :href="route('collections.show', [$collection])" class="mb-2 name"/>
            </li>
            @endforeach
        </ul>
    </div>
    @endif

    @if($keyword->calls->count())
    <div class="mb-8">
        <h2 class="text-sm font-bold mb-2">{{ $keyword->calls->count() }} Calls</h2>
        <ul>
            @foreach($keyword->calls as $call)
            <li class="inline">
                <x-links.default :label="$call->label" :href="route('calls.show', [$call])" class="mb-2 name"/>
            </li>
            @endforeach
        </ul>
    </div>
    @endif

    @if($keyword->images->count())
    <div class="mb-4">
        <h2 class="text-sm font-bold mb-2">{{ $keyword->images->count() }} Images</h2>
        <p class="text-sm">This keyword has <x-links.default href="/?keyword={{ $keyword->id }}" label="{{ $keyword->images->count() }} images" /> associated. Preview of the first up to 12 images...</p>
        <div class="my-4 list grid grid-cols-1 lg:grid-cols-3 xl:grid-cols-6 gap-4 grid-flow-row">
        @foreach($keyword->images as $image)
            @if($loop->index > 11)
                @break
            @endif
            <a href="{{ route('images.show', [$image]) }}">
                <img class="inline-block mr-2 w-full"
                    src="https://sipi.participatory-archives.ch/{{$image->base_path != '' ? $image->base_path.'/' : ''}}{{$image->signature}}.jp2/full/360,/0/default.jpg"
                    alt="{{$image->title}}" title="{{$image->title}}">
            </a>
        @endforeach
        </div>
        @if($keyword->images->count() > 12)
        <p class="mt-4">
            <a class="py-2 px-4 text-lg bg-black rounded-full text-white" href="/?keyword={{ $keyword->id }}">Show all images</a>
        </p>
        @endif
    </div>
    @endif
</div>
@endsection