routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AgentController;
use App\Http\Controllers\CallController;
use App\Http\Controllers\CallEntryController;
use App\Http\Controllers\CollectionController;
use App\Http\Controllers\DateController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\KeywordController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\PlaceController;

use App\Models\Collection;
use App\Models\Date;
use App\Models\Image;
use App\Models\Keyword;
use App\Models\Place;

use AnthonyMartin\GeoLocation\GeoPoint;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $request) {
    $images_otd = [];
    $total_count = Image::count();

    while (count($images_otd) <= 6) {
        srand(floor(time()/86400)+count($images_otd));
        $image = Image::find(rand(0, $total_count));
        $images_otd[] = $image;
    }

    return view('frontend/home', [
        'tagcloud' => $request->has('tagcloud'),
        'collections' => Collection::where('origin', 'pia')->latest()->take(20)->get(),
        'images_otd' => $images_otd
    ]);
});

Route::resource('collections', CollectionController::class);
Route::resource('images', ImageController::class);
Route::resource('keywords', KeywordController::class);
Route::resource('agents', AgentController::class);
Route::resource('places', PlaceController::class);
Route::resource('notes', NoteController::Class);
Route::resource('maps', MapController::Class);
Route::resource('calls', CallController::Class);
Route::resource('callentries', CallEntryController::Class);
Route::resource('dates', DateController::Class);

Route::get('/calls/{id}/entry', [CallController::class, 'entry'])->name('maps.images');

Route::get('/images/{id}/similar', [ImageController::class, 'findSimilar'])->name('images.similar');

Route::get('/maps/{id}/images', [MapController::class, 'images'])->name('maps.images');
Route::patch('/maps/{id}/imagesUpdate', [MapController::class, 'imagesUpdate'])->name('maps.imagesUpdate');

Route::get('/collections/{id}/csv',
    [FrontendController::class, 'csv'])->name('collections.csv');
Route::post('/collections/{id}/upload-image',
    [CollectionController::class, 'uploadImage'])->name('collections.uploadImage');
Route::post('/collections/{id}/upload-documents',
    [CollectionController::class, 'uploadDocuments'])->name('collections.uploadDocuments');
Route::get('/collections/{id}/map',
    [CollectionController::class, 'map'])->name('collections.map');
Route::get('/collections/{id}/copy',
    [CollectionController::class, 'copy'])->name('collections.copy');
Route::post('/collections/{id}/do-copy',
    [CollectionController::class, 'doCopy'])->name('collections.doCopy');
Route::get('/collections/{id}/timeline',
    [CollectionController::class, 'timeline'])->name('collections.timeline');
Route::get('/collections/{id}/memory',
    [CollectionController::class, 'memory'])->name('collections.memory');
Route::get('/collections/{id}/export',
    [CollectionController::class, 'export'])->name('collections.export');

Route::get('/by-coordinates', function (Request $request) {
    return view('frontend/partials/search-by-coordinates');
})->name('search.byCoordinates');
Route::get('/by-dates', function (Request $request) {
    return view('frontend/partials/search-by-dates');
})->name('search.byDates');

Route::get('/nearby', function(Request $request) {
    if ($request->latitude) {

        $geopoint = new GeoPoint($request->latitude, $request->longitude);
        $bounding_box = $geopoint->boundingBox($request->distance / 1000, 'km');

        $places = Place
            ::where('longitude', '>=', $bounding_box->getMinLongitude())
            ->where('latitude', '>=', $bounding_box->getMinLatitude())
            ->where('longitude', '<=', $bounding_box->getMaxLongitude())
            ->where('latitude', '<=', $bounding_box->getMaxLatitude())
            ->get();

        $image_ids = [];

        foreach($places as $key => $place) {
            foreach($place->images as $key => $image) {
                array_push($image_ids, $image->id);
            }
        }

        return view('frontend/nearby', [
            'images' => Image::whereIn('id', $image_ids)->get()
        ]);
    }

    return view('frontend/nearby');
});

/* custom error handling */
Route::fallback(function() {
    return view('errors/404', [
        'image' => Image::inRandomOrder()->first(),
        'collections' => Collection::inRandomOrder()->limit(3)->get(),
        'keywords' => Keyword::inRandomOrder()->limit(3)->get()
    ]);
});

/* statistics */
Route::get('/stats', function(Request $request) {
    $images_total = Image::count();

    $images_wo_date = Image::doesnthave('date')->count();
    $images_wo_location = Image::doesnthave('place')->count();
    $images_wo_keywords = Image::doesnthave('keywords')->count();

    $images_wo_date_location = Image::doesnthave('date')->where('place_id', null)->count();
    $images_wo_keywords_location = Image::doesnthave('keywords')->where('place_id', null)->count();
    $images_wo_date_keywords = Image::doesnthave('keywords')->doesnthave('dates')->count();
    $images_wo_date_keywords_location = Image::doesnthave('keywords')->doesnthave('date')->where('place_id', null)->count();

    $images_w_date_location = Image::has('date')->where('place_id', '!=', null)->count();
    $images_w_date_keywords = Image::has('date')->has('keywords')->count();
    $images_w_keywords_location = Image::has('keywords')->where('place_id', '!=', null)->count();
    $images_w_date_keywords_location = Image::has('keywords')->has('date')->where('place_id', '!=', null)->count();

    $images_w_acc_1 = Image::whereHas('date', function($q){
        $q->where('accuracy', '1');
    })->count();
    $images_w_acc_2 = Image::whereHas('date', function($q){
        $q->where('accuracy', '2');
    })->count();
    $images_w_acc_3 = Image::whereHas('date', function($q){
        $q->where('accuracy', '3');
    })->count();
    $images_w_date_range = Image::whereHas('date', function($q){
        $q->whereNotNull('end_date');
    })->count();

//number_format(100 / $images * $images_wo, 2)

    echo('<table cellpadding="8" border style="font-family: sans-serif;">');
    echo('<tr>');
    echo('<td>Total Image Count</td>');
    echo('<td>'.number_format($images_total, 0, '.', '\'').'</td>');
    echo('<td></td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images without date</td>');
    echo('<td>'.number_format($images_wo_date, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date, 0, '.', '\'').'% (of total images)</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without location</td>');
    echo('<td>'.number_format($images_wo_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without keywords</td>');
    echo('<td>'.number_format($images_wo_keywords, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images with neither date nor a location</td>');
    echo('<td>'.number_format($images_wo_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with neither keywords nor a location</td>');
    echo('<td>'.number_format($images_wo_keywords_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with neither date nor keywords</td>');
    echo('<td>'.number_format($images_wo_date_keywords, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without anything</td>');
    echo('<td>'.number_format($images_wo_date_keywords_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images with date and location</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_date_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with keywords and location</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with date and keywords</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_date_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with everything</td>');
    echo('<td>'.number_format($images_w_date_keywords_location, 0, '.', '\'').'</td>');

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

use App\Models\Image;
use App\Models\Keyword;
use App\Models\Collection;
use App\Models\Comment;

class FrontendController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function csv($id)
    {
        $collection = Collection::find($id);

        $headers = array(
            "Content-type" => "text/csv",
            "Content-Disposition" => "attachment; filename=file.csv",
            "Pragma" => "no-cache",
            "Cache-Control" => "must-revalidate, post-check=0, pre-check=0",
            "Expires" => "0"
        );
    
        $columns = array(
            'salsah_id', 'oldnr', 'signature', 'title', 'file_name', 'sequence_number',
            'object_type', 'model_type', 'format',
            'keywords','collections','comments','people','dates','location',
        );
    
        $callback = function() use ($collection, $columns)
        {
            $file = fopen('php://output', 'w');
            fputcsv($file, $columns);
    
            foreach($collection->images as $image) {

                $data = [
                    $image->salsah_id,
                    $image->oldnr,
                    $image->signature,
                    $image->original_title,
                    $image->original_file_name,
                    $image->sequence_number,

                    '', '', '', 
                    '', '', '', '', '', '',
                ];

                if($image->objectType) {
                    $data[6] = $image->objectType->label .'/'. $image->objectType->comment;
                }
                if($image->modelType) {
                    $data[7] = $image->modelType->label .'/'. $image->modelType->comment;
                }
                if($image->format) {
                    $data[8] = $image->format->label .'/'. $image->format->comment;
                }

                if($image->keywords) {
                    foreach($image->keywords as $keyword) {
                        $data['9'] .= $keyword->label . ', ';
                    }
                }
                if($image->collections) {
                    foreach($image->collections as $collection) {
                        $data['10'] .= $collection->label . ', ';
                    }
                }
                if($image->comments) {
                    foreach($image->comments as $comment) {
                        $data['11'] .= $comment->comment . ', ';
                    }
                }
                if($image->people) {
                    foreach($image->people as $person) {
                        $data['12'] .= $person->name . ', ';
                    }
                }
                if($image->location) {
                    $data['13'] = $image->location->label;
                }

                $data['9'] = rtrim($data['9'], ', ');
                $data['10'] = rtrim($data['10'], ', ');
                $data['11'] = rtrim($data['11'], ', ');
                $data['12'] = rtrim($data['12'], ', ');

                fputcsv($file, $data);
            }
            fclose($file);
        };

        return response()->streamDownload($callback, $collection->label.'.csv');
    }
}

resources/views/frontend/partials/aside-collections.blade.php
<div id="collections"
    class="min-h-screen max-h-screen w-20 bg-white border-left border-gray-500 transition-all overflow-y-auto overflow-x-hidden"
    :style="expand_collections ? 'width: 640px;' : ''">

    <div>
        <div class="flex px-3 py-2 justify-between">
            <button @click="expand_collections = ! expand_collections">
                <span x-show="! expand_collections">
                    <svg class="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
                </span>
                <span x-show="expand_collections">
                    <svg class="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                </span>
            </button>
            <a class="leading-10 hover:underline font-bold" href="{{ route('collections.index') }}" x-show="expand_collections">All Collections</a>
            <span class="inline-block w-10 h-10 leading-10">
            </span>
        </div>

        <ul>
        @foreach ($collections as $collection)
            <li class="flex justify-between px-3 py-2 border-b border-gray-400">
                <span
                    class="block w-10 h-10 leading-10 rounded-full border border-gray-500 text-center text-xs cursor-pointer"
                    @click="expand_collections = ! expand_collections">{{ $collection->images()->count() }}</span>
                <a class="leading-10 hover:underline" href="{{ route('collections.show', [$collection]) }}" x-show="expand_collections">{{ $collection->label }}</a>
                <span class="inline-block w-10 h-10 leading-10 border border-gray-500 text-center text-xs" x-show="expand_collections">
                    {{ $collection->maps()->count() + $collection->notes()->count() + $collection->documents()->count() }}
                </span>
            </li>
        @endforeach
        </ul>
    </div>
</div>

resources/views/frontend/partials/search-by-coordinates.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PIA Search and Curate</title>

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/app.css">
    
    @yield('styles')

</head>

<body>
    
<div id="map" class="mb-4" style="height: 400px; width: 400px;"></div>
<x-links.cta id="search" href="javascript:;" label="Search on this map section" target="_top"/>

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin="" />
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>

<script>

    document.addEventListener('DOMContentLoaded', function () {
        
        let center = [46.818188, 8.227512],
            map = L.map('map', {
                center: center,
                zoom: 8,
                maxZoom: 18,
                doubleClickZoom: false
            });

        L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            maxZoom: 18,
            id: 'mapbox/light-v10',
            tileSize: 512,
            zoomOffset: -1,
            accessToken: 'pk.eyJ1IjoidGhnaWV4IiwiYSI6ImNrcjF5Z2ZxZDI2bWYydnFhMWw0eDV2YjIifQ.CZJtOXLy-IZeI6a5ia8Lzw'
        }).addTo(map);

        map.on('moveend', function(e) {
            var bounds = map.getBounds();
            
            document.querySelector('#search').href = '/?coordinates='+bounds.getNorthWest().lat+','+bounds.getNorthWest().lng+','+bounds.getSouthEast().lat+','+bounds.getSouthEast().lng;
        });


    });

</script>

</body>
</html>

resources/views/frontend/partials/search-by-dates.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PIA Search and Curate</title>

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/app.css">
    
    @yield('styles')

</head>

<body>
        <div>
            <label for="from" class="inline-block" style="width: 100px">On/From</label>
            <input type="date" name="from" class="border-b" oninput="on_change(this)">
        </div>
        <div class="mb-8">
            <label for="to" class="inline-block" style="width: 100px">To</label>
            <input type="date" name="to" class="border-b" oninput="on_change(this)">
        </div>
        <x-links.cta id="search" href="javascript:;" label="Search with these dates" target="_top"/>
    </div>
</div>

<script>

    let from = document.querySelector('input[name="from"]'),
        to = document.querySelector('input[name="to"]');

    function on_change(){
        document.querySelector('#search').href = '/?dates='+from.value;

        if(to.value) {
            document.querySelector('#search').href += ','+to.value;
        } else {
            document.querySelector('#search').href += ','+from.value;
        }
    }

</script>

</body>
</html>