routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AgentController;
use App\Http\Controllers\CallController;
use App\Http\Controllers\CallEntryController;
use App\Http\Controllers\CollectionController;
use App\Http\Controllers\DateController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\KeywordController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\PlaceController;

use App\Models\Collection;
use App\Models\Date;
use App\Models\Image;
use App\Models\Keyword;
use App\Models\Place;

use AnthonyMartin\GeoLocation\GeoPoint;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $request) {
    $images_otd = [];
    $total_count = Image::count();

    while (count($images_otd) <= 6) {
        srand(floor(time()/86400)+count($images_otd));
        $image = Image::find(rand(0, $total_count));
        $images_otd[] = $image;
    }

    return view('frontend/home', [
        'tagcloud' => $request->has('tagcloud'),
        'collections' => Collection::where('origin', 'pia')->latest()->take(20)->get(),
        'images_otd' => $images_otd
    ]);
});

Route::resource('collections', CollectionController::class);
Route::resource('images', ImageController::class);
Route::resource('keywords', KeywordController::class);
Route::resource('agents', AgentController::class);
Route::resource('places', PlaceController::class);
Route::resource('notes', NoteController::Class);
Route::resource('maps', MapController::Class);
Route::resource('calls', CallController::Class);
Route::resource('callentries', CallEntryController::Class);
Route::resource('dates', DateController::Class);

Route::get('/calls/{id}/entry', [CallController::class, 'entry'])->name('maps.images');

Route::get('/images/{id}/similar', [ImageController::class, 'findSimilar'])->name('images.similar');

Route::get('/maps/{id}/images', [MapController::class, 'images'])->name('maps.images');
Route::patch('/maps/{id}/imagesUpdate', [MapController::class, 'imagesUpdate'])->name('maps.imagesUpdate');

Route::get('/collections/{id}/csv',
    [FrontendController::class, 'csv'])->name('collections.csv');
Route::post('/collections/{id}/upload-image',
    [CollectionController::class, 'uploadImage'])->name('collections.uploadImage');
Route::post('/collections/{id}/upload-documents',
    [CollectionController::class, 'uploadDocuments'])->name('collections.uploadDocuments');
Route::get('/collections/{id}/map',
    [CollectionController::class, 'map'])->name('collections.map');
Route::get('/collections/{id}/copy',
    [CollectionController::class, 'copy'])->name('collections.copy');
Route::post('/collections/{id}/do-copy',
    [CollectionController::class, 'doCopy'])->name('collections.doCopy');
Route::get('/collections/{id}/timeline',
    [CollectionController::class, 'timeline'])->name('collections.timeline');
Route::get('/collections/{id}/memory',
    [CollectionController::class, 'memory'])->name('collections.memory');
Route::get('/collections/{id}/export',
    [CollectionController::class, 'export'])->name('collections.export');

Route::get('/by-coordinates', function (Request $request) {
    return view('frontend/partials/search-by-coordinates');
})->name('search.byCoordinates');
Route::get('/by-dates', function (Request $request) {
    return view('frontend/partials/search-by-dates');
})->name('search.byDates');

Route::get('/nearby', function(Request $request) {
    if ($request->latitude) {

        $geopoint = new GeoPoint($request->latitude, $request->longitude);
        $bounding_box = $geopoint->boundingBox($request->distance / 1000, 'km');

        $places = Place
            ::where('longitude', '>=', $bounding_box->getMinLongitude())
            ->where('latitude', '>=', $bounding_box->getMinLatitude())
            ->where('longitude', '<=', $bounding_box->getMaxLongitude())
            ->where('latitude', '<=', $bounding_box->getMaxLatitude())
            ->get();

        $image_ids = [];

        foreach($places as $key => $place) {
            foreach($place->images as $key => $image) {
                array_push($image_ids, $image->id);
            }
        }

        return view('frontend/nearby', [
            'images' => Image::whereIn('id', $image_ids)->get()
        ]);
    }

    return view('frontend/nearby');
});

/* custom error handling */
Route::fallback(function() {
    return view('errors/404', [
        'image' => Image::inRandomOrder()->first(),
        'collections' => Collection::inRandomOrder()->limit(3)->get(),
        'keywords' => Keyword::inRandomOrder()->limit(3)->get()
    ]);
});

/* statistics */
Route::get('/stats', function(Request $request) {
    $images_total = Image::count();

    $images_wo_date = Image::doesnthave('date')->count();
    $images_wo_location = Image::doesnthave('place')->count();
    $images_wo_keywords = Image::doesnthave('keywords')->count();

    $images_wo_date_location = Image::doesnthave('date')->where('place_id', null)->count();
    $images_wo_keywords_location = Image::doesnthave('keywords')->where('place_id', null)->count();
    $images_wo_date_keywords = Image::doesnthave('keywords')->doesnthave('dates')->count();
    $images_wo_date_keywords_location = Image::doesnthave('keywords')->doesnthave('date')->where('place_id', null)->count();

    $images_w_date_location = Image::has('date')->where('place_id', '!=', null)->count();
    $images_w_date_keywords = Image::has('date')->has('keywords')->count();
    $images_w_keywords_location = Image::has('keywords')->where('place_id', '!=', null)->count();
    $images_w_date_keywords_location = Image::has('keywords')->has('date')->where('place_id', '!=', null)->count();

    $images_w_acc_1 = Image::whereHas('date', function($q){
        $q->where('accuracy', '1');
    })->count();
    $images_w_acc_2 = Image::whereHas('date', function($q){
        $q->where('accuracy', '2');
    })->count();
    $images_w_acc_3 = Image::whereHas('date', function($q){
        $q->where('accuracy', '3');
    })->count();
    $images_w_date_range = Image::whereHas('date', function($q){
        $q->whereNotNull('end_date');
    })->count();

//number_format(100 / $images * $images_wo, 2)

    echo('<table cellpadding="8" border style="font-family: sans-serif;">');
    echo('<tr>');
    echo('<td>Total Image Count</td>');
    echo('<td>'.number_format($images_total, 0, '.', '\'').'</td>');
    echo('<td></td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images without date</td>');
    echo('<td>'.number_format($images_wo_date, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date, 0, '.', '\'').'% (of total images)</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without location</td>');
    echo('<td>'.number_format($images_wo_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without keywords</td>');
    echo('<td>'.number_format($images_wo_keywords, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images with neither date nor a location</td>');
    echo('<td>'.number_format($images_wo_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with neither keywords nor a location</td>');
    echo('<td>'.number_format($images_wo_keywords_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with neither date nor keywords</td>');
    echo('<td>'.number_format($images_wo_date_keywords, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images without anything</td>');
    echo('<td>'.number_format($images_wo_date_keywords_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_wo_date_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr><td colspan="3">&nbsp;</td></tr>');
    echo('<tr>');
    echo('<td>Images with date and location</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_date_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with keywords and location</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_keywords_location, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with date and keywords</td>');
    echo('<td>'.number_format($images_w_date_location, 0, '.', '\'').'</td>');
    echo('<td>'.number_format(100 / $images_total * $images_w_date_keywords, 0, '.', '\'').'%</td>');
    echo('</tr>');
    echo('<tr>');
    echo('<td>Images with everything</td>');
    echo('<td>'.number_format($images_w_date_keywords_location, 0, '.', '\'').'</td>');

resources/views/images/edit.blade.php
@extends('base')

@section('styles')
    <link rel="stylesheet" href="{{ asset('node_modules/leaflet/dist/leaflet.css') }}">
    <style>

        .leaflet-container {
            background: #181818;
        }

    </style>
@endsection

@section('content')
<div class="bg-gray-100 min-h-screen" x-data="{cols: 3}">
    <div class="flex" id="searchable-list" >
        <div class="fixed h-screen w-1/2 overflow-hidden">
            <div id="iiif-image" class="w-full min-h-full"></div>
        </div>

        <div class="fixed left-1/2 h-screen w-1/2 pr-36 bg-white overflow-y-auto">
            <div class="pt-14 pb-20 pl-14 pr-4">

                <form action="{{ route('images.update', [$image]) }}" method="post">
                    @csrf
                    @method('patch')

                <div class="mb-12 ">
                    <h2 class="text-4xl text-center w-full">
                        <input type="text" name="title" value="{{ $image->title ?? '' }}" class="w-full border border-gray-300 p-1 px-2">
                    </h2>
                </div>

                <table class="w-full">
                    <thead class="text-xs">
                        <tr>
                            <td class="pb-2 w-1/3">Field</td>
                            <td class="pb-2">Value</td>
                        </tr>
                    </thead>
                    <tr>
                        <td>SALSAH ID</td>
                        <td>
                            <input type="number" name="salsah_id" value="{{ $image->salsah_id ?? '' }}" class="w-full border border-gray-300 p-1 px-2">
                        </td>
                    </tr>
                    <tr>
                        <td>Old Nr</td>
                        <td>
                            <input type="text" name="oldnr" value="{{ $image->oldnr ?? '' }}" class="w-full border border-gray-300 p-1 px-2">
                        </td>
                    </tr>
                    <tr>
                        <td>Sequence Number</td>
                        <td>
                            <input type="text" name="sequence_number" value="{{ $image->sequence_number ?? '' }}" class="w-full border border-gray-300 p-1 px-2">
                        </td>
                    </tr>

                    {{--<tr>
                        <td class="w-1/3">Verso</td>
                        <td>
                            @if ($image->verso)
                                <a href="{{ route('images.show', [$id => $image->verso]) }}">Verso</a>
                            @else
                            –
                            @endif
                        </td>
                    </tr>--}}
                    <tr>
                        <td class="w-1/3">Object Type</td>
                        <td>
                            <select name="object_type_id" class="w-full slim">
                                <option value="">-</option>
                                @foreach ($object_types as $object_type)
                                    <option value="{{ $object_type->id }}" {{ ($image->objectType && $image->objectType->id == $object_type->id) ? 'selected' : '' }}>{{ $object_type->label }}</option>
                                @endforeach
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Model Type</td>
                        <td>
                            <select name="model_type_id" class="w-full slim">
                                <option value="">-</option>
                                @foreach ($model_types as $model_type)
                                    <option value="{{ $model_type->id }}" {{ ($image->modelType && $image->modelType->id == $model_type->id) ? 'selected' : '' }}>{{ $model_type->label }}</option>
                                @endforeach
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Format</td>
                        <td>
                            <select name="format_id" class="w-full slim">
                                <option value="">-</option>
                                @foreach ($formats as $format)
                                    <option value="{{ $format->id }}" {{ ($image->format && $image->format->id == $format->id) ? 'selected' : '' }}>{{ $format->label }} / {{ $format->comment }}</option>
                                @endforeach
                            </select>
                        </td>
                    </tr>
                </table>
                
                <div class="my-6">
                    <h3 class="mb-1 text-xs">Keywords</h3>
                    <div class="mb-2">
                        <select name="keywords[]" class="w-full slim" multiple>
                            <option value="">-</option>
                            @foreach ($keywords as $keyword)
                                <option value="{{ $keyword->id }}" {{ $image->keywords->contains($keyword->id) ? 'selected' : '' }}>{{ $keyword->label }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="mb-6">
                    <h3 class="mb-2 text-xs">Collections</h3>
                    <div>
                        <select name="collections[]" class="w-full slim" multiple>
                            <option value="">-</option>
                            @foreach ($collections as $collection)
                                <option value="{{ $collection->id }}" {{ $image->collections->contains($collection->id) ? 'selected' : '' }}>{{ $collection->label }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                

                <div class="mb-6">
                    <h3 class="mb-2 text-xs">Comments</h3>
                    @foreach ($image->comments as $comment)
                        @if ($comment->comment)
                            <p class="mb-2 text-sm">– {{ $comment->comment }}</p>
                        @endif
                    @endforeach
                    <textarea name="append_comment" placeholder="Add new comment" class="w-full mt-1 border border-gray-300 p-1 px-2"></textarea>
                </div>
                
                <div class="mb-6">
                    <h3 class="mb-2 text-xs">Copyright</h3>
                    <div>
                        <select name="copyright_id" class="w-full slim">
                            <option value="">-</option>
                            @foreach ($agents as $agent)
                                <option value="{{ $agent->id }}" {{ $image->copyright_id == $agent->id ? 'selected' : '' }}>{{ $agent->name }}</option>
                            @endforeach
                        </select>
                        <input type="text" name="append_copyright" placeholder="Name of new copyright holder" class="w-full mt-1 border border-gray-300 p-1 px-2">
                    </div>
                </div>
                <div class="mb-6">
                    <h3 class="mb-2 text-xs">License</h3>
                    <td>
                        <input type="text" name="license" value="{{ $image->license ?? '' }}" class="w-full border border-gray-300 p-1 px-2" placeholder="URL to license">
                    </td>
                </div>

                
                <div class="mb-6">
                    <h3 class="mb-2 text-xs">Agents</h3>
                    <div>
                        <select name="agents[]" class="w-full slim" multiple>
                            <option value="">-</option>
                            @foreach ($agents as $agent)
                                <option value="{{ $agent->id }}" {{ $image->agents->contains($agent->id) ? 'selected' : '' }}>{{ $agent->name }}</option>
                            @endforeach
                        </select>
                        <input type="text" name="append_agent" placeholder="Name of new person" class="w-full mt-1 border border-gray-300 p-1 px-2">
                    </div>
                </div>

                <div class="mb-6">
                    <h3 class="mb-2 text-xs">Date</h3>
                    <div>
                        <div class="flex">
                            @if($image->date)
                                @if ($image->date->date)
                                    <span class="inline-block py-1 px-3 text-xs rounded-full bg-black text-white mr-2 mb-2">{{ date('d. M Y', strtotime($image->date->date)); }}</span>
                                @endif
                                @if ($image->date->end_date)
                                    <span class="inline-block py-1 px-3 text-xs rounded-full bg-black text-white mr-2 mb-2">{{ date('d. M Y', strtotime($image->date->end_date)); }}</span>
                                @endif
                                @if ($image->date->date_string)
                                    <span class="inline-block py-1 px-3 text-xs underline mr-2 mb-2">{{ $image->date->date_string }}</span>
                                @endif
                            @else
                            &mdash;
                            @endif
                        </div>
                        <input type="date" name="append_date" placeholder="Add new date" class="w-full border border-gray-300 p-1 px-2">
                    </div>
                </div>

                <div class="mb-6">
                    <h3 class="mb-2 text-xs">Place</h3>
                    <div>
                        <select name="place_id" class="w-full slim">
                            <option value="">-</option>
                            @foreach ($places as $place)
                                <option value="{{ $place->id }}" {{ ($image->place && $image->place->id == $place->id) ? 'selected' : '' }}>{{ $place->label }}</option>
                            @endforeach
                        </select>
                        <input type="text" name="append_place" placeholder="Name of new place" class="w-full mt-1 border border-gray-300 p-1 px-2">
                    </div>
                </div>

                <div class="flex justify-between fixed bottom-0 left-1/2 w-1/2 pl-8 py-2 pr-28 border-t leading-10 border-gray-300 bg-white">
                    <button type="submit" class="hover:underline">Save info</button>
                    <a class="hover:underline" href="{{ route('images.show', [$image]) }}">View image</a>
                </div>

                </form>
                
            </div>
        </div>
    </div>

    <aside id="sidebar"
        x-data="{expand_collections: false}"
        @mouseleave="expand_collections = false;"
        class="flex fixed top-0 right-0 transform transition min-h-screen shadow-2xl z-50 print-hidden">
        
        <livewire:collections-aside />
    </aside>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('node_modules/leaflet/dist/leaflet.js') }}"></script>
    <script src="{{ asset('node_modules/leaflet-iiif/leaflet-iiif.js') }}"></script>

    <script>

        document.addEventListener('DOMContentLoaded', () => {
            var image = L.map('iiif-image', {
                center: [0, 0],
                crs: L.CRS.Simple,
                zoom: 0,
            });

            L.tileLayer.iiif('https://sipi.participatory-archives.ch/{{$image->base_path}}/{{$image->signature}}.jp2/info.json').addTo(image);

            document.querySelectorAll('select.slim').forEach(el => {
                console.log(el)
                new SlimSelect({
                    select: el,
                });
            });
        })

    </script>
@endsection

resources/views/images/show.blade.php
@extends('base')

@section('styles')
    <link rel="stylesheet" href="{{ asset('node_modules/leaflet/dist/leaflet.css') }}">
    <style>

        .leaflet-container {
            background: #181818;
        }

    </style>
@endsection

@section('content')
<div class="bg-gray-100 min-h-screen" x-data="{cols: 3}">
    <div class="flex flex-col md:flex-row" id="searchable-list" >
        <div class="md:fixed h-80 md:h-screen md:w-1/2 overflow-hidden">
            <div id="iiif-image" class="w-full min-h-full"></div>
        </div>

        <div class="md:fixed md:left-1/2 md:h-screen md:w-1/2 md:pr-14 bg-white overflow-y-auto">
            @include('images.partials.details')
        </div>
    </div>

    <aside id="sidebar">
        <livewire:collections-aside />
    </aside>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('node_modules/leaflet/dist/leaflet.js') }}"></script>
    <script src="{{ asset('node_modules/leaflet-iiif/leaflet-iiif.js') }}"></script>

    <script>

        document.addEventListener('DOMContentLoaded', () => {
            var image = L.map('iiif-image', {
                center: [0, 0],
                crs: L.CRS.Simple,
                zoom: 0,
            });

            L.tileLayer.iiif('https://sipi.participatory-archives.ch/{{$image->base_path}}/{{$image->signature}}.jp2/info.json').addTo(image);
        })

    </script>
@endsection

resources/views/images/similar.blade.php
@extends('base')

@section('content')
<div class="bg-gray-100 min-h-screen" x-data="{cols: 3}">
    <div class="flex" id="searchable-list" >
        <div class="fixed bg-black h-screen w-1/2 p-4 overflow-y-auto">
            <div>
                <section class="my-10 print-hidden">
                    <div class="flex gap-6 items-left">
                        <div class="flex gap-2 items-center print-hidden" x-data>
                            <a class="text-xs mr-1 ml-2 underline text-white" href="{{ route('images.similar', [$image]) }}?category=visualtextcoembedding">visualtextcoembedding</a>
                            <a class="text-xs mr-1 ml-2 underline text-white" href="{{ route('images.similar', [$image]) }}?category=localcolor">localcolor</a>
                            <a class="text-xs mr-1 underline text-white" href="{{ route('images.similar', [$image]) }}?category=globalcolor">globalcolor</a>
                            <a class="text-xs mr-1 underline text-white" href="{{ route('images.similar', [$image]) }}?category=localfeatures">localfeatures</a>
                        </a>
                    </div>
                </section>
            
                <main>
                    <div id="images" class="pb-20">
                        @include('collections.partials.display-grid', ['images' => $images])
                    </div>
                </main>
            </div>
        </div>

        <div class="fixed left-1/2 h-screen w-1/2 pr-36 bg-white overflow-y-auto">
            @include('images.partials.details', ['header' => $image])
        </div>
    </div>

    <aside id="sidebar"
        x-data="{expand_collections: false}"
        @mouseleave="expand_collections = false;"
        class="flex fixed top-0 right-0 transform transition min-h-screen shadow-2xl z-50 print-hidden">
        
        <livewire:collections-aside />
    </aside>
</div>
@endsection